#!/bin/bash

# Arguments
if [[ -z $1 || -z $2 || -z $3 ]]; then
	echo "Usage: color_fade <clr_from> <clr_to> <fraction>"
	echo "   eg. color_fade \"#FF0000\" \"#00FF00\" 0.5"
	exit 1
fi
r1=${1:1:2}
g1=${1:3:2}
b1=${1:5:2}
r2=${2:1:2}
g2=${2:3:2}
b2=${2:5:2}
if [[ $(echo "$3 > 1" | bc) -eq 1 ]]; then
	frac=1
else
	if [[ $(echo "$3 < 0" | bc) -eq 1 ]]; then
		frac=0
	else
		frac=$3
	fi
fi

# Deltas
function hex_to_dec {
	printf "%d" "0x$1"
}
function hex_diff {
	echo $(( $(hex_to_dec "$2") - $(hex_to_dec "$1") ))
}
rd=$(echo "$(hex_diff "$r1" "$r2") * $frac" | bc)
gd=$(echo "$(hex_diff "$g1" "$g2") * $frac" | bc)
bd=$(echo "$(hex_diff "$b1" "$b2") * $frac" | bc)

# Results
rr=$(echo "$(hex_to_dec "$r1")" + "$rd" | bc)
gr=$(echo "$(hex_to_dec "$g1")" + "$gd" | bc)
br=$(echo "$(hex_to_dec "$b1")" + "$bd" | bc)

function round_dec {
	printf "%.0f" "$1"
}
printf "#%02x%02x%02x" "$(round_dec "$rr")" "$(round_dec "$gr")" "$(round_dec "$br")"
